build:
  maxIssues: 0

config:
  validation: true

processors:
  active: true

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false

formatting:
  active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: [ Composable ]  # keeps PascalCase composables like ExpenseerTheme()